version: 2
jobs:
  build:
    docker:
      - image: mcgizzle/alphabetsoup-ci

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt +test:compile makeMicrosite

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.coursier/cache
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # run tests!
      - run: cat /dev/null | sbt +macrosJVM/test +alphabetSoupJVM/test +mtlJVM/test
